Description: >

  This template deploys a highly available ECS Jenkins cluster using an AutoScaling Group, with
  ECS hosts distributed across multiple Availability Zones.

Parameters:
  KeyName:
    Description: Amazon EC2 Key Pair
    Type: "AWS::EC2::KeyPair::KeyName"
    Default: dap-dev-private-kp

  ECSInstanceType:
    Description: Which instance type should we use to build the ECS cluster?
    Type: String
    Default: t2.small

  ECSClusterSize:
    Description: How many ECS hosts do you want to initially deploy?
    Type: Number
    Default: 1

  Bucket:
    Type: String
    Description: Name of the bucket where the id_rsa key is located in an encrypted form
    Default: dap-jenkins-service

  TemplateBucket:
    Type: String
    Description: Name of the bucket where the id_rsa key is located in an encrypted form
    Default: dap-jenkins-service

  RegionName:
    Type: String
    Description: Region name where the bucket is located.
    Default: us-east-1

  KMSRegionName:
    Type: String
    Description: Region name where the KMS KEY is located.
    Default: us-east-1

  AccountNumber:
    Description: Account number is needed for configuring ecs cluster
    Type: String
    Default: 846018127931

  JenkinsPassword:
    Description: Jenkins password to Set
    Type: String
    Default: topsecretpassword2018

  RepositoryName:
    Description: ECR name where the jenkins image is located
    Type: String
    Default: dap/dap-jenkins-master

  JenkinsTag:
    Description: Tag of the jenkins image
    Type: String
    Default: test-v01030400

  SlaveRepositoryName:
    Description: ECR name where the jenkins image is located
    Type: String
    Default: dap/dap-jenkins-slave

  SlaveTag:
    Description: Tag of the jenkins slave image
    Type: String
    Default: test-v01030400

  VPC:
    Description: VPC to deploy to
    Type: AWS::EC2::VPC::Id
    Default: vpc-0f821c57cc4e1e9fa

  ALBSubnets:
    Description: Subnets to which to deploy ALB
    Type: List<AWS::EC2::Subnet::Id>
    Default: "subnet-002c02746c2b126bd,subnet-0fa9ad8801e05c205"

  ECSHostSubnets:
    Description: Subnets to which to deploy ECS Tasks
    Type: List<AWS::EC2::Subnet::Id>
    Default: "subnet-0f1e53bc431f3bcad,subnet-0a813c845dd40db9c"

Resources:
  SecurityGroups:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${TemplateBucket}/infrastructure/security-groups.yaml
      Parameters:
        EnvironmentName: !Ref AWS::StackName
        VPC: !Ref VPC

  ALB:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${TemplateBucket}/infrastructure/load-balancers.yaml
      Parameters:
        EnvironmentName: !Ref AWS::StackName
        VPC: !Ref VPC
        Subnets: !Ref ALBSubnets
        SecurityGroup: !GetAtt SecurityGroups.Outputs.LoadBalancerSecurityGroup

  ECS:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${TemplateBucket}/infrastructure/ecs-cluster.yaml
      Parameters:
        EnvironmentName: !Ref AWS::StackName
        InstanceType: !Ref ECSInstanceType
        ClusterSize: !Ref ECSClusterSize
        VPC: !Ref VPC
        SecurityGroup: !GetAtt SecurityGroups.Outputs.ECSHostSecurityGroup
        Subnets: !Ref ECSHostSubnets
        KeyName: !Ref KeyName
        Bucket: !Ref Bucket
        RegionName: !Ref AWS::Region
        KMSRegionName: !Ref KMSRegionName

  JenkinsService:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${TemplateBucket}/services/jenkins-service/service.yaml
      Parameters:
        VPC: vpc-0f821c57cc4e1e9fa
        Cluster: !GetAtt ECS.Outputs.Cluster
        DesiredCount: 1
        AccountNumber: !Ref AWS::AccountId
        JenkinsPassword: !Ref JenkinsPassword
        RegionName: !Ref AWS::Region
        RepositoryName: !Ref RepositoryName
        JenkinsTag: !Ref JenkinsTag
        SlaveRepositoryName: !Ref SlaveRepositoryName
        SlaveTag: !Ref SlaveTag
        Listener: !GetAtt ALB.Outputs.Listener
        Path: /*

Outputs:
  WebsiteServiceUrl:
    Description: The URL endpoint for the website service
    Value: !Join ["", [!GetAtt ALB.Outputs.LoadBalancerUrl, "/"]]
